//! Parser for Swift show-dependencies deplock files.
//!
//! Extracts dependency information from `swift-show-dependencies.deplock` files
//! created by the dependency-inspector tool.
//!
//! # Supported Formats
//! - `swift-show-dependencies.deplock` - Swift dependency graph JSON
//!
//! # Implementation Notes
//! - Format: JSON with nested dependency tree
//! - Generated by deplock tool or `swift package show-dependencies`
//! - Extracts full dependency graph with versions (beyond Python which only extracts name)
//! - Spec: https://forums.swift.org/t/swiftpm-show-dependencies-without-fetching-dependencies/51154

use std::fs;
use std::path::Path;

use log::warn;
use serde::{Deserialize, Serialize};

use crate::models::{DatasourceId, Dependency, PackageData, PackageType};

use super::PackageParser;

const PACKAGE_TYPE: PackageType = PackageType::Swift;

fn default_package_data() -> PackageData {
    PackageData {
        package_type: Some(PACKAGE_TYPE),
        primary_language: Some("Swift".to_string()),
        datasource_id: Some(DatasourceId::SwiftPackageShowDependencies),
        ..Default::default()
    }
}

pub struct SwiftShowDependenciesParser;

#[derive(Debug, Deserialize, Serialize)]
struct SwiftDeplock {
    name: Option<String>,
    version: Option<String>,
    url: Option<String>,
    #[serde(default)]
    dependencies: Vec<SwiftDependency>,
}

#[derive(Debug, Deserialize, Serialize, Clone)]
struct SwiftDependency {
    identity: Option<String>,
    name: Option<String>,
    version: Option<String>,
    url: Option<String>,
    #[serde(default)]
    dependencies: Vec<SwiftDependency>,
}

impl PackageParser for SwiftShowDependenciesParser {
    const PACKAGE_TYPE: PackageType = PACKAGE_TYPE;

    fn is_match(path: &Path) -> bool {
        path.to_str()
            .is_some_and(|p| p.ends_with("/swift-show-dependencies.deplock"))
    }

    fn extract_packages(path: &Path) -> Vec<PackageData> {
        let content = match fs::read_to_string(path) {
            Ok(c) => c,
            Err(e) => {
                warn!(
                    "Failed to read swift-show-dependencies.deplock {:?}: {}",
                    path, e
                );
                return vec![default_package_data()];
            }
        };

        vec![parse_swift_show_dependencies(&content)]
    }
}

pub(crate) fn parse_swift_show_dependencies(content: &str) -> PackageData {
    let data: SwiftDeplock = match serde_json::from_str(content) {
        Ok(d) => d,
        Err(e) => {
            warn!("Failed to parse swift-show-dependencies.deplock: {}", e);
            return default_package_data();
        }
    };

    let dependencies = flatten_dependencies(&data.dependencies);

    PackageData {
        package_type: Some(PACKAGE_TYPE),
        primary_language: Some("Swift".to_string()),
        name: data.name,
        version: data.version,
        homepage_url: data.url,
        dependencies,
        datasource_id: Some(DatasourceId::SwiftPackageShowDependencies),
        ..Default::default()
    }
}

fn flatten_dependencies(deps: &[SwiftDependency]) -> Vec<Dependency> {
    let mut result = Vec::new();
    let mut queue: Vec<(&SwiftDependency, bool)> = deps.iter().map(|d| (d, true)).collect();

    while let Some((dep, is_direct)) = queue.pop() {
        if let Some(name) = &dep.name {
            let purl = if let Some(url) = &dep.url {
                if url.contains("github.com") {
                    let parts: Vec<&str> = url.trim_end_matches(".git").split('/').collect();
                    if parts.len() >= 2 {
                        let owner = parts[parts.len() - 2];
                        let repo = parts[parts.len() - 1];
                        Some(format!("pkg:swift/github.com/{}/{}", owner, repo))
                    } else {
                        Some(format!("pkg:swift/{}", name))
                    }
                } else {
                    Some(format!("pkg:swift/{}", name))
                }
            } else {
                Some(format!("pkg:swift/{}", name))
            };

            result.push(Dependency {
                purl,
                extracted_requirement: dep.version.clone(),
                scope: Some("dependencies".to_string()),
                is_runtime: Some(true),
                is_optional: Some(false),
                is_pinned: dep.version.as_ref().map(|v| !v.contains("unspecified")),
                is_direct: Some(is_direct),
                resolved_package: None,
                extra_data: None,
            });
        }

        for child in &dep.dependencies {
            queue.push((child, false));
        }
    }

    result
}

crate::register_parser!(
    "Swift show-dependencies deplock file",
    &["*swift-show-dependencies.deplock"],
    "swift",
    "Swift",
    Some(
        "https://forums.swift.org/t/swiftpm-show-dependencies-without-fetching-dependencies/51154"
    ),
);
