// SPDX-FileCopyrightText: nexB Inc. and others
// ScanCode is a trademark of nexB Inc.
// SPDX-FileCopyrightText: Provenant contributors
// SPDX-License-Identifier: Apache-2.0
// Derived from ScanCode Toolkit (Apache-2.0); modified. See NOTICE.

//! Parser for Swift show-dependencies deplock files.
//!
//! Extracts dependency information from `swift-show-dependencies.deplock` files
//! created by the dependency-inspector tool.
//!
//! # Supported Formats
//! - `swift-show-dependencies.deplock` - Swift dependency graph JSON
//!
//! # Implementation Notes
//! - Format: JSON with nested dependency tree
//! - Generated by deplock tool or `swift package show-dependencies`
//! - Extracts full dependency graph with versions (beyond Python which only extracts name)
//! - Spec: https://forums.swift.org/t/swiftpm-show-dependencies-without-fetching-dependencies/51154

use std::path::Path;

use crate::parser_warn as warn;
use serde::{Deserialize, Serialize};

use crate::models::{DatasourceId, Dependency, PackageData, PackageType, ResolvedPackage};
use crate::parsers::utils::{
    MAX_ITERATION_COUNT, RecursionGuard, capped_iteration_limit, read_file_to_string,
    truncate_field,
};

use super::PackageParser;

const PACKAGE_TYPE: PackageType = PackageType::Swift;

fn default_package_data() -> PackageData {
    PackageData {
        package_type: Some(PACKAGE_TYPE),
        primary_language: Some("Swift".to_string()),
        datasource_id: Some(DatasourceId::SwiftPackageShowDependencies),
        ..Default::default()
    }
}

pub struct SwiftShowDependenciesParser;

#[derive(Debug, Deserialize, Serialize)]
struct SwiftDeplock {
    name: Option<String>,
    version: Option<String>,
    url: Option<String>,
    #[serde(default)]
    dependencies: Vec<SwiftDependency>,
}

#[derive(Debug, Deserialize, Serialize, Clone)]
struct SwiftDependency {
    identity: Option<String>,
    name: Option<String>,
    version: Option<String>,
    url: Option<String>,
    #[serde(default)]
    dependencies: Vec<SwiftDependency>,
}

impl PackageParser for SwiftShowDependenciesParser {
    const PACKAGE_TYPE: PackageType = PACKAGE_TYPE;

    fn is_match(path: &Path) -> bool {
        path.file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name == "swift-show-dependencies.deplock")
    }

    fn extract_packages(path: &Path) -> Vec<PackageData> {
        let content = match read_file_to_string(path, None) {
            Ok(c) => c,
            Err(e) => {
                warn!(
                    "Failed to read swift-show-dependencies.deplock {:?}: {}",
                    path, e
                );
                return vec![default_package_data()];
            }
        };

        vec![parse_swift_show_dependencies(&content)]
    }

    fn metadata() -> Vec<super::metadata::ParserMetadata> {
        vec![super::metadata::ParserMetadata {
            description: "Swift show-dependencies deplock file",
            file_patterns: &["*swift-show-dependencies.deplock"],
            package_type: "swift",
            primary_language: "Swift",
            documentation_url: Some(
                "https://forums.swift.org/t/swiftpm-show-dependencies-without-fetching-dependencies/51154",
            ),
        }]
    }
}

pub(crate) fn parse_swift_show_dependencies(content: &str) -> PackageData {
    let data: SwiftDeplock = match serde_json::from_str(content) {
        Ok(d) => d,
        Err(e) => {
            warn!("Failed to parse swift-show-dependencies.deplock: {}", e);
            return default_package_data();
        }
    };

    let dependencies = flatten_dependencies(&data.dependencies);
    let version = normalize_version(data.version);
    let homepage_url = normalize_remote_url(data.url.clone());
    let purl = create_root_purl(
        data.name.as_deref(),
        data.url.as_deref(),
        version.as_deref(),
    );

    PackageData {
        package_type: Some(PACKAGE_TYPE),
        primary_language: Some("Swift".to_string()),
        name: data.name.map(truncate_field),
        version: version.map(truncate_field),
        homepage_url: homepage_url.map(truncate_field),
        dependencies,
        datasource_id: Some(DatasourceId::SwiftPackageShowDependencies),
        purl,
        ..Default::default()
    }
}

fn flatten_dependencies(deps: &[SwiftDependency]) -> Vec<Dependency> {
    let mut result = Vec::new();

    for dep in deps {
        let mut guard: RecursionGuard<String> = RecursionGuard::new();
        let mut depth_guard = RecursionGuard::<()>::depth_only();
        flatten_dependency(dep, true, &mut result, &mut guard, &mut depth_guard);
    }

    result
}

fn flatten_dependency(
    dep: &SwiftDependency,
    is_direct: bool,
    result: &mut Vec<Dependency>,
    guard: &mut RecursionGuard<String>,
    depth_guard: &mut RecursionGuard<()>,
) {
    if guard.exceeded() || depth_guard.exceeded() {
        warn!("Recursion depth exceeded in swift dependency flattening");
        return;
    }

    if result.len() >= MAX_ITERATION_COUNT {
        return;
    }

    let dep_key = dep
        .identity
        .as_deref()
        .or(dep.name.as_deref())
        .unwrap_or("")
        .to_string();
    if !dep_key.is_empty() && guard.enter(dep_key.clone()) {
        return;
    }

    if let Some(dependency) = build_dependency(dep, is_direct, depth_guard) {
        result.push(dependency);
    }

    for child in &dep.dependencies {
        flatten_dependency(child, false, result, guard, depth_guard);
    }

    if !dep_key.is_empty() {
        guard.leave(dep_key);
    }
}

fn build_dependency(
    dep: &SwiftDependency,
    is_direct: bool,
    guard: &mut RecursionGuard<()>,
) -> Option<Dependency> {
    if guard.descend() {
        warn!("Recursion depth exceeded in swift dependency building");
        return None;
    }

    let name = truncate_field(dep.name.as_ref()?.clone());
    let version = normalize_version(dep.version.clone());
    let purl = create_dependency_purl(dep, version.as_deref());
    let nested_limit = capped_iteration_limit(
        dep.dependencies.len(),
        "swift show-dependencies nested dependencies",
    );
    let nested_dependencies = dep
        .dependencies
        .iter()
        .take(nested_limit)
        .filter_map(|child| build_dependency(child, true, guard))
        .collect();

    guard.ascend();

    Some(Dependency {
        purl: purl.map(truncate_field),
        extracted_requirement: version.clone().map(truncate_field),
        scope: Some("dependencies".to_string()),
        is_runtime: None,
        is_optional: None,
        is_pinned: Some(version.is_some()),
        is_direct: Some(is_direct),
        resolved_package: Some(Box::new(ResolvedPackage {
            primary_language: Some("Swift".to_string()),
            download_url: None,
            sha1: None,
            sha256: None,
            sha512: None,
            md5: None,
            is_virtual: true,
            extra_data: None,
            dependencies: nested_dependencies,
            repository_homepage_url: None,
            repository_download_url: None,
            api_data_url: None,
            datasource_id: Some(DatasourceId::SwiftPackageShowDependencies),
            purl: None,
            ..ResolvedPackage::new(
                PACKAGE_TYPE,
                truncate_field(extract_namespace(dep.url.as_deref()).unwrap_or_default()),
                name,
                truncate_field(version.clone().unwrap_or_default()),
            )
        })),
        extra_data: None,
    })
}

/// swift requires a namespace (VCS host + owner). When the dependency has no
/// source URL to derive one from, omit the PURL rather than emit a
/// namespace-less, spec-invalid one.
fn create_dependency_purl(dep: &SwiftDependency, version: Option<&str>) -> Option<String> {
    let url = dep.url.as_deref()?;
    let (namespace, name) = parse_url_namespace_and_name(url)?;
    crate::parsers::utils::namespaced_purl("swift", &namespace, &name, version)
}

/// As with dependencies, the root package needs a namespace derived from its
/// source URL; without one the PURL is omitted.
fn create_root_purl(
    name: Option<&str>,
    url: Option<&str>,
    version: Option<&str>,
) -> Option<String> {
    let name = name?.trim();
    if name.is_empty() {
        return None;
    }
    let (namespace, _) = parse_url_namespace_and_name(url?)?;
    crate::parsers::utils::namespaced_purl("swift", &namespace, name, version)
}

fn normalize_version(version: Option<String>) -> Option<String> {
    version.and_then(|v| {
        let trimmed = v.trim();
        if trimmed.is_empty() || trimmed == "unspecified" {
            None
        } else {
            Some(trimmed.to_string())
        }
    })
}

fn normalize_remote_url(url: Option<String>) -> Option<String> {
    url.and_then(|value| {
        let trimmed = value.trim();
        if trimmed.starts_with("http://") || trimmed.starts_with("https://") {
            Some(trimmed.to_string())
        } else {
            None
        }
    })
}

fn extract_namespace(url: Option<&str>) -> Option<String> {
    parse_url_namespace_and_name(url?).map(|(namespace, _)| namespace)
}

fn parse_url_namespace_and_name(url: &str) -> Option<(String, String)> {
    let trimmed = url.trim().trim_end_matches('/').trim_end_matches(".git");
    let without_scheme = trimmed
        .strip_prefix("https://")
        .or_else(|| trimmed.strip_prefix("http://"))?;
    let mut parts = without_scheme.split('/');
    let host = crate::parsers::utils::url_authority_host(parts.next()?);
    let owner = parts.next()?;
    let repo = parts.next()?;

    Some((format!("{}/{}", host, owner), repo.to_string()))
}
