FROM docker.io/library/debian:bookworm-slim

LABEL org.opencontainers.image.title="Jitsi Broadcasting Infrastructure (jibri)" \
      org.opencontainers.image.description="Components for recording and/or streaming a conference." \
      org.opencontainers.image.url="https://github.com/jitsi/jibri" \
      org.opencontainers.image.source="https://github.com/jitsi/docker-jitsi-meet" \
      org.opencontainers.image.documentation="https://jitsi.github.io/handbook/" \
      org.opencontainers.image.version="stable-8960-1" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.revision="abcdef123456"
