#[cfg(test)]
use std::fs;
#[cfg(test)]
use std::io::Result;
#[cfg(test)]
use std::path::Path;

const GENERATED_KEYWORDS_LOWERED: &[&str] = &[
    "generated by",
    "auto-generated",
    "automatically generated",
    "generated on",
    "last generated on",
    "do not edit this file",
    "it is machine generated",
    "automatically created by",
    "following schema fragment specifies the",
    "this code is generated",
    "generated by cython",
    "this file was automatically generated by",
    "this file is generated by",
    "generated file, do not edit",
    "this is an autogenerated file",
    "generated by the protocol buffer compiler",
    "generated code -- do not edit",
    "makefile.in generated by automake",
    "generated automatically by aclocal",
    "generated by gnu autoconf",
    "this file was automatically generated",
];

#[cfg(test)]
pub fn generated_code_hints(path: &Path) -> Result<Vec<String>> {
    let content = fs::read(path)?;
    Ok(generated_code_hints_from_bytes(&content))
}

pub fn generated_code_hints_from_bytes(content: &[u8]) -> Vec<String> {
    let text = String::from_utf8_lossy(content);
    let mut hints = Vec::new();

    for line in text.lines().take(150) {
        let lowered = line.trim().to_ascii_lowercase();
        if GENERATED_KEYWORDS_LOWERED
            .iter()
            .any(|keyword| lowered.contains(keyword))
        {
            hints.push(lowered.chars().take(100).collect());
        }
    }

    hints
}
