use super::test_utils::{dir, file};
use super::*;
use std::path::Path;

#[test]
fn mark_generated_files_detects_known_generated_header() {
    let temp = tempfile::tempdir().expect("tempdir should be created");
    let dir_path = temp.path().join("simple");
    std::fs::create_dir_all(&dir_path).expect("dir should be created");
    let generated_path = dir_path.join("generated_6.c");
    let plain_path = dir_path.join("plain.c");
    std::fs::write(
        &generated_path,
        "/* DO NOT EDIT THIS FILE - it is machine generated */\n",
    )
    .expect("generated fixture should be written");
    std::fs::write(&plain_path, "int main(void) { return 0; }\n")
        .expect("plain fixture should be written");

    let mut files = vec![
        dir("simple"),
        file(
            generated_path
                .strip_prefix(temp.path())
                .unwrap()
                .to_str()
                .unwrap(),
        ),
        file(
            plain_path
                .strip_prefix(temp.path())
                .unwrap()
                .to_str()
                .unwrap(),
        ),
    ];

    mark_generated_files(&mut files, Some(temp.path()));

    assert_eq!(files[0].is_generated, Some(false));
    assert_eq!(files[1].is_generated, Some(true));
    assert_eq!(files[2].is_generated, Some(false));
}

#[test]
fn generated_hint_samples_match_scancode_expectations() {
    let root = Path::new("testdata/summarycode-golden/generated");
    let samples = [
        (
            root.join("simple/generated_1.java"),
            vec![
                "// this file was generated by the javatm architecture for xml binding(jaxb) reference implementation".to_string(),
                "// generated on: 2011.08.01 at 11:35:59 am cest".to_string(),
            ],
        ),
        (
            root.join("simple/generated_2.java"),
            vec!["* this class was generated by the jax-ws ri.".to_string()],
        ),
        (
            root.join("simple/generated_3.java"),
            vec![
                "// this file was generated by the javatm architecture for xml binding(jaxb) reference implementation".to_string(),
                "// generated on: 2013.11.15 at 04:17:00 pm cet".to_string(),
            ],
        ),
        (
            root.join("simple/generated_4.java"),
            vec!["/* this class was automatically generated".to_string()],
        ),
        (
            root.join("simple/generated_5.java"),
            vec![
                "* <p>the following schema fragment specifies the expected content contained within this class.".to_string(),
            ],
        ),
        (
            root.join("simple/generated_6.c"),
            vec!["/* do not edit this file - it is machine generated */".to_string()],
        ),
        (
            root.join("simple/configure"),
            vec!["# generated by gnu autoconf 2.64 for apache couchdb 1.0.1.".to_string()],
        ),
        (
            root.join("jspc/web.xml"),
            vec!["<!--automatically created by apache jakarta tomcat jspc.".to_string()],
        ),
    ];

    for (path, expected) in samples {
        let actual = generated_code_hints(&path).unwrap();
        assert_eq!(actual, expected, "path={}", path.display());
    }
}
