use std::path::Path;
use std::sync::Arc;

use serde_json::Value;

use super::test_utils::{
    compare_scan_json_values, dir, file, normalize_paths_for_test, normalize_scan_json,
};
use super::*;
use crate::progress::{ProgressMode, ScanProgress};
use crate::scanner::{TextDetectionOptions, collect_paths, process_collected};

#[test]
fn mark_generated_files_detects_known_generated_header() {
    let temp = tempfile::tempdir().expect("tempdir should be created");
    let dir_path = temp.path().join("simple");
    std::fs::create_dir_all(&dir_path).expect("dir should be created");
    let generated_path = dir_path.join("generated_6.c");
    let plain_path = dir_path.join("plain.c");
    std::fs::write(
        &generated_path,
        "/* DO NOT EDIT THIS FILE - it is machine generated */\n",
    )
    .expect("generated fixture should be written");
    std::fs::write(&plain_path, "int main(void) { return 0; }\n")
        .expect("plain fixture should be written");

    let mut files = vec![
        dir("simple"),
        file(
            generated_path
                .strip_prefix(temp.path())
                .unwrap()
                .to_str()
                .unwrap(),
        ),
        file(
            plain_path
                .strip_prefix(temp.path())
                .unwrap()
                .to_str()
                .unwrap(),
        ),
    ];

    mark_generated_files(&mut files, Some(temp.path()));

    assert_eq!(files[0].is_generated, Some(false));
    assert_eq!(files[1].is_generated, Some(true));
    assert_eq!(files[2].is_generated, Some(false));
}

#[test]
fn generated_hint_samples_match_scancode_expectations() {
    let root = Path::new("testdata/summarycode-golden/generated");
    let samples = [
        (
            root.join("simple/generated_1.java"),
            vec![
                "// this file was generated by the javatm architecture for xml binding(jaxb) reference implementation".to_string(),
                "// generated on: 2011.08.01 at 11:35:59 am cest".to_string(),
            ],
        ),
        (
            root.join("simple/generated_2.java"),
            vec!["* this class was generated by the jax-ws ri.".to_string()],
        ),
        (
            root.join("simple/generated_3.java"),
            vec![
                "// this file was generated by the javatm architecture for xml binding(jaxb) reference implementation".to_string(),
                "// generated on: 2013.11.15 at 04:17:00 pm cet".to_string(),
            ],
        ),
        (
            root.join("simple/generated_4.java"),
            vec!["/* this class was automatically generated".to_string()],
        ),
        (
            root.join("simple/generated_5.java"),
            vec![
                "* <p>the following schema fragment specifies the expected content contained within this class.".to_string(),
            ],
        ),
        (
            root.join("simple/generated_6.c"),
            vec!["/* do not edit this file - it is machine generated */".to_string()],
        ),
        (
            root.join("simple/configure"),
            vec!["# generated by gnu autoconf 2.64 for apache couchdb 1.0.1.".to_string()],
        ),
        (
            root.join("jspc/web.xml"),
            vec!["<!--automatically created by apache jakarta tomcat jspc.".to_string()],
        ),
    ];

    for (path, expected) in samples {
        let actual = generated_code_hints(&path).unwrap();
        assert_eq!(actual, expected, "path={}", path.display());
    }
}

#[test]
fn generated_cli_fixture_matches_expected_file_flags() {
    let generated_root = Path::new("testdata/summarycode-golden/generated");
    let fixture_root = generated_root.join("simple");
    let progress = Arc::new(ScanProgress::new(ProgressMode::Quiet));
    let collected = collect_paths(&fixture_root, 0, &[]);
    let mut files = process_collected(
        &collected,
        progress,
        None,
        false,
        &TextDetectionOptions::default(),
    )
    .files;

    files.push(dir("simple"));
    normalize_paths_for_test(
        &mut files,
        generated_root
            .to_str()
            .expect("fixture path should be UTF-8"),
    );
    mark_generated_files(&mut files, Some(generated_root));

    let actual = serde_json::json!({
        "files": files
            .into_iter()
            .map(|file| serde_json::json!({
                "path": file.path,
                "type": file.file_type,
                "is_generated": file.is_generated,
                "scan_errors": file.scan_errors,
            }))
            .collect::<Vec<_>>()
    });
    let expected: Value = serde_json::from_str(
        &std::fs::read_to_string("testdata/summarycode-golden/generated/cli.expected.json")
            .expect("expected generated cli fixture should be readable"),
    )
    .expect("expected generated cli fixture should parse");

    let mut actual_normalized = actual;
    let mut expected_normalized = expected;
    normalize_scan_json(&mut actual_normalized, None);
    normalize_scan_json(&mut expected_normalized, None);

    if let Err(error) = compare_scan_json_values(&actual_normalized, &expected_normalized, "") {
        panic!(
            "Generated CLI fixture mismatch: {}\nactual={}\nexpected={}",
            error,
            serde_json::to_string_pretty(&actual_normalized).unwrap_or_default(),
            serde_json::to_string_pretty(&expected_normalized).unwrap_or_default()
        );
    }
}
